App\Entity\Recipe:
    attributes:
      id:
        groups: ['recipe']
      title:
        groups: ['recipe']
      text:
        groups: ['recipe']
      img:
        groups: ['recipe']
      prepTime:
        groups: ['recipe']
      dificulty:
        groups: ['recipe']
      people:
        groups: ['recipe']
      rating:
        groups: ['recipe']
      ingredients:
        groups: ['recipe']
      steps:
        groups: ['recipe']