App\Entity\Recipe:
    attributes:
      id:
        groups: ['recipe']
      title:
        groups: ['recipe']
      text:
        groups: ['recipe']
      rating:
        groups: ['recipe']
      ingredients:
        groups: ['recipe']
      steps:
        groups: ['recipe']