App\Entity\Step:
    attributes:
      id:
        groups: ['step']
      title:
        groups: ['step']
      stepNo:
        groups: ['step']
      stepImg:
        groups: ['step']
      stepText:
        groups: ['step']