App\Entity\User:
    attributes:
      id:
        groups: ['user']
      email:
        groups: ['user']
      recipes:
        groups: ['user']
      picture:
        groups: ['user']
      name:
        groups: ['user']