controllers:
    resource: ../src/Controller/
    type: annotation

api:
    resource: ../src/Controller/Api
    type: annotation
    prefix: /api

api_login_check:
    path: /api/login_check

kernel:
    resource: ../src/Kernel.php
    type: annotation
