controllers:
    resource: ../src/Controller/
    type: annotation

api:
    resource: ../src/Controller/Api
    type: annotation
    prefix: /

kernel:
    resource: ../src/Kernel.php
    type: annotation
